<?php

global $bmOptions;

// do not edit this file
// all values are set via config settings or upon use

$bmOptions['SSLcert'] = '';

$bmOptions['SSLkey'] = '';

$bmOptions['secret'] = '';

$bmOptions['notificationEmail'] = '';

$bmOptions['notificationURL'] = '';

$bmOptions['redirectURL'] = '';

$bmOptions['currency'] = '';

$bmOptions['physical'] = 'true';

$bmOptions['fullNotifications'] = 'true';

$bmOptions['transactionSpeed'] = 'low';

$bmOptions['bitmerch_url'] = 'https://bitmerch.com';
